### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by wyli**
@Nic-Ma revised the main readme
I think "introduction of technical highlights" could be "Feature highlights".
otherwise the captions is taking too much space on the webpage

Screenshot 2020-06-26 at 18 58 35

### Status
**Ready**

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Did you miss some modification in this PR? I can't find the  "Feature highlights" change.
Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Did you miss some modification in this PR? I can't find the "Feature highlights" change.
> Thanks.

thanks I updated it

**Comment by wyli** [comment]
@Nic-Ma in the module figure, we could make the research block more generic: 
`Research - implementation of recently published deep learning research in medical imaging, such as COVID-19 CT models, automatic model parallelism.`

**Comment by Nic-Ma** [comment]
> @Nic-Ma in the module figure, we could make the research block more generic:
> `Research - implementation of recently published deep learning research in medical imaging, such as COVID-19 CT models, automatic model parallelism.`

Sure, updated in the latest commit.
Thanks.

**Comment by wyli** [comment]
> > @Nic-Ma in the module figure, we could make the research block more generic:
> > `Research - implementation of recently published deep learning research in medical imaging, such as COVID-19 CT models, automatic model parallelism.`
> 
> Sure, updated in the latest commit.
> Thanks.

could you please update the boxes in the figure? "COVID-19" should be more specific, something like "COVID-19 CT segmentation". And not sure if we want to put FL in the box, please align with Prerna.

**Comment by Nic-Ma** [comment]
Sure, updated in the latest commit.
Thanks.

**Comment by wyli** [comment]
> Sure, updated in the latest commit.
> Thanks.

just saw that you add new figures, but I didn't generate those images, they were downloaded from the internet, I'm not sure if we can use them freely. please generate new ones, we just need some label images. https://github.com/Nic-Ma/MONAI/blob/add-arch-chart-docs/docs/source/highlights.md#8-post-processing-transforms-for-model-output

**Comment by Nic-Ma** [comment]
OK, I am working on the `DecathlonDataset`, will try to update the post transform chart with Spleen data soon.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli , updated the chart in the latest commit.
Thanks.

**Pull request merged**
